### ISSUE TITLE
How to generate the binary ?

### ISSUE THREAD

**Issue by kwccoin** [bittysoftware/bitty_xmas_bauble_device_code#1]
Try to take up the challenge but may I ask how you generate the binary ? Those .h files ? Use g++?  Any makefile?  For your kind advice.

**Comment by bittysoftware** [comment]
Hi, information on setting up your tools for offline, C/C++ development are here:

https://lancaster-university.github.io/microbit-docs/offline-toolchains/ 

Good luck :-)
